### PR TITLE
Add sets

### PR DESCRIPTION
**Pull request by janajri**

### CODE REVIEW

**Comment by janajri** [comment]
@buckhx I added a bunch here to try and match the apis we were using in the app. There were three primary options that we needed here: 

messagediff.TreatAsSet
messagediff.Field
messagediff.CompareUsing
messagediff.TreatRepeatedFieldsAsSets

I've implemented all -- although CompareUsing is not complete. I'm going to hold off on this one until I'm working on the package that requires it. Currently just stubbed.

**Comment by janajri** [comment]
FYI, these functions are primarily used on test packages.

**Comment by janajri** [comment]
fyi @thdxr @jstaehle

**Comment by buckhx** [comment]
@janajri Prob want to add some simple tests for our usage on these new methods

**Pull request merged**
